/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Admin;

import static Admin.AddStudent.db;
import static Admin.Approval.add;
import static Admin.Approval.appId;
import static Admin.Approval.db;
import static Admin.Approval.email;
import static Admin.Approval.lname;
import static Admin.Approval.mi;
import static Admin.Approval.pw;
import static Admin.Approval.studNo;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drewn
 */
public class ApprovalForm extends javax.swing.JInternalFrame {

    static String db = "jdbc:mysql://localhost:3306/sis";
    static String appId, studNo, mi, lname, add, email, pw;

    /**
     * Creates new form ApprovalForm
     */
    public ApprovalForm() {
        initComponents();
        viewData();
                setDefaultRow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblApproval = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnDisapprove = new javax.swing.JButton();

        tblApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ApprovalId", "StudentNumber", "MiddleInitial", "LastName", "Address", "Email", "Password"
            }
        ));
        tblApproval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblApprovalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblApproval);

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDisapprove.setText("Disapprove");
        btnDisapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisapproveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDisapprove, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisapprove, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisapproveActionPerformed
        // TODO add your handling code here:
        disapprove();
        clearTable();
        viewData();
    }//GEN-LAST:event_btnDisapproveActionPerformed

    private void tblApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblApprovalMouseClicked
        // TODO add your handling code here:
        getRow();

    }//GEN-LAST:event_tblApprovalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        approve();
        removeReq();
        clearTable();
        viewData();
    }//GEN-LAST:event_jButton1ActionPerformed

    void viewData() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "SELECT * FROM approval";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            ResultSet rslt = pstmnt.executeQuery();
            //      isa-isahin yung data
            while (rslt.next()) {
                String appId = rslt.getString("ApprovalId");
                String studno = rslt.getString("StudentNumber");
                String mi = rslt.getString("MiddleInitial");
                String lname = rslt.getString("LastName");
                String add = rslt.getString("Address");
                String pw = rslt.getString("Pass_word");
                String email = rslt.getString("Email");

                String data[] = {appId, studno, mi, lname, add, email, pw,};
                DefaultTableModel tbl = (DefaultTableModel) tblApproval.getModel();

                tbl.addRow(data);
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void getRow() {
        DefaultTableModel tbl = (DefaultTableModel) tblApproval.getModel();
        int selectedRowIndex = tblApproval.getSelectedRow();

        appId = tbl.getValueAt(selectedRowIndex, 0).toString();
        studNo = tbl.getValueAt(selectedRowIndex, 1).toString();
        mi = tbl.getValueAt(selectedRowIndex, 2).toString();
        lname = tbl.getValueAt(selectedRowIndex, 3).toString();
        add = tbl.getValueAt(selectedRowIndex, 4).toString();
        email = tbl.getValueAt(selectedRowIndex, 5).toString();
        pw = tbl.getValueAt(selectedRowIndex, 6).toString();
    }

    void setDefaultRow() {
        DefaultTableModel tbl = (DefaultTableModel) tblApproval.getModel();
        if (tblApproval.getRowCount() > 0) {
            tblApproval.setRowSelectionInterval(0, 0);
            getSelectedRow();
        }

    }

    void getSelectedRow() {
        DefaultTableModel tbl = (DefaultTableModel) tblApproval.getModel();

        appId = tbl.getValueAt(0, 0).toString();
        studNo = tbl.getValueAt(0, 1).toString();
        mi = tbl.getValueAt(0, 2).toString();
        lname = tbl.getValueAt(0, 3).toString();
        add = tbl.getValueAt(0, 4).toString();
        email = tbl.getValueAt(0, 5).toString();
        pw = tbl.getValueAt(0, 6).toString();
    }

    void disapprove() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "DELETE FROM approval WHERE ApprovalId = ?";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            pstmnt.setString(1, appId);

            pstmnt.executeUpdate();
            showMessageDialog(this, "Approval Disapproved");

        } catch (SQLException err) {
            err.printStackTrace();
        }

    }

    void removeReq() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "DELETE FROM approval WHERE ApprovalId = ?";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            pstmnt.setString(1, appId);

            pstmnt.executeUpdate();

        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void approve() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "UPDATE `student_info` SET `MiddleInitial`=?,`LastName`=?,`Address`=?,"
                    + "`Pass_word`=?, `Email`=?"
                    + "WHERE StudentNumber = ?";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
//            pstmnt.setString(1, txtStudentNumber.getText());
            pstmnt.setString(1, mi);
            pstmnt.setString(2, lname);
            pstmnt.setString(3, add);
            pstmnt.setString(4, pw);
            pstmnt.setString(5, email);
            pstmnt.setString(6, studNo);

            pstmnt.executeUpdate();
            showMessageDialog(this, "Changes Approved");

        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblApproval.getModel();
        model.setRowCount(0);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisapprove;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblApproval;
    // End of variables declaration//GEN-END:variables
}
