/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Admin;

import static Admin.AddStudent.db;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drewn
 */
public class BatchForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form BatchForm
     */
    public BatchForm() {
        initComponents();
        viewProgramData(null);
        viewStudentData(null);
    }

    void viewProgramData(String fieldName) {
        String qry;
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            if (fieldName == null) {
                qry = "SELECT * FROM program";
            } else {
                qry = "SELECT * FROM program WHERE BatchNumber ='" + fieldName + "'";
            }
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            ResultSet rslt = pstmnt.executeQuery();
            //      isa-isahin yung data
            while (rslt.next()) {
                String programId = rslt.getString("ProgramId");
                String programTitle = rslt.getString("ProgramTitle");
                String trainer = rslt.getString("Trainer");
                String batchNo = rslt.getString("BatchNumber");
                String startDate = rslt.getString("StartDate");
                String endDate = rslt.getString("EndDate");

                String data[] = {programId, programTitle, trainer, batchNo, startDate, endDate,};
                DefaultTableModel tbl = (DefaultTableModel) tblBatch.getModel();

                tbl.addRow(data);
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void clearBatchTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudentInfo.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblBatch.getModel();

        model.setRowCount(0);
        model2.setRowCount(0);
    }

    void viewStudentData(String fieldName) {
        String qry;
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            if (fieldName == null) {
                qry = "SELECT * FROM student_info";
            } else {
                qry = "SELECT * FROM student_info WHERE BatchNo ='" + fieldName + "'";
            }
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            ResultSet rslt = pstmnt.executeQuery();
            //      isa-isahin yung data
            while (rslt.next()) {
                String studno = rslt.getString("StudentNumber");
                String fname = rslt.getString("FirstName");
                String mi = rslt.getString("MiddleInitial");
                String lname = rslt.getString("LastName");
                String add = rslt.getString("Address");
                String req = rslt.getString("Requirement_Status");
                String pw = rslt.getString("Pass_word");
                String batchno = rslt.getString("BatchNo");
                String prog = rslt.getString("ProgramTitle");
                String email = rslt.getString("Email");
                String grade = rslt.getString("Grade");

                String data[] = {studno, fname, mi, lname, add, req, pw, batchno,
                    prog, email, grade};
                DefaultTableModel tbl = (DefaultTableModel) tblStudentInfo.getModel();

                tbl.addRow(data);
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearchBatch = new javax.swing.JButton();
        txtBatchNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBatch = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentInfo = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        btnSearchBatch.setText("Search Batch");
        btnSearchBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchBatchMouseClicked(evt);
            }
        });
        btnSearchBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBatchActionPerformed(evt);
            }
        });

        txtBatchNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchNoActionPerformed(evt);
            }
        });

        tblBatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProgramId", "ProgramTitle", "Trainer", "BatchNumber", "StartDate", "EndDate"
            }
        ));
        jScrollPane2.setViewportView(tblBatch);

        tblStudentInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Number", "First Name", "Middle Inital", "Last Name", "Address", "Requirement Status", "Password", "BatchNo", "ProgramTitle", "Email", "Grade"
            }
        ));
        tblStudentInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudentInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnSearchBatch))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchBatch)
                    .addComponent(txtBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBatchMouseClicked
        clearBatchTable();
        viewProgramData(txtBatchNo.getText());
        viewStudentData(txtBatchNo.getText());
    }//GEN-LAST:event_btnSearchBatchMouseClicked

    private void btnSearchBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBatchActionPerformed

    private void txtBatchNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatchNoActionPerformed

    private void tblStudentInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentInfoMouseClicked
        // TODO add your handling code here:
        //        getRow();
    }//GEN-LAST:event_tblStudentInfoMouseClicked

      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatchForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchBatch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBatch;
    private javax.swing.JTable tblStudentInfo;
    private javax.swing.JTextField txtBatchNo;
    // End of variables declaration//GEN-END:variables
}
