/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Admin;

import static Admin.ProgramForm.db;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drewn
 */
public class ProgramIntForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProgramIntForm
     */
    public ProgramIntForm() {
        initComponents();
        viewData();
        setDefaultRow();
        this.getContentPane().setBackground(new Color(204, 255, 204));
        this.setPreferredSize(new Dimension(1393, 876));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProgID = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtProgramTitle = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtTrainer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBtchNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStart = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProgramInfo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbAscDesc = new javax.swing.JComboBox<>();
        cbFieldName = new javax.swing.JComboBox<>();
        btnSort = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1400, 875));
        setPreferredSize(new java.awt.Dimension(1400, 876));

        txtProgID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProgID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgIDActionPerformed(evt);
            }
        });

        txtEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ProgramID");

        btnUpdate.setBackground(new java.awt.Color(102, 255, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setText("Update Program");
        btnUpdate.setMaximumSize(new java.awt.Dimension(131, 31));
        btnUpdate.setMinimumSize(new java.awt.Dimension(131, 31));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtProgramTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProgramTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramTitleActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Add Program");
        btnAdd.setMaximumSize(new java.awt.Dimension(131, 31));
        btnAdd.setMinimumSize(new java.awt.Dimension(131, 31));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Progam Title");

        btnDelete.setBackground(new java.awt.Color(102, 255, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Delete Program");
        btnDelete.setMaximumSize(new java.awt.Dimension(131, 31));
        btnDelete.setMinimumSize(new java.awt.Dimension(131, 31));
        btnDelete.setPreferredSize(new java.awt.Dimension(131, 31));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        txtTrainer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrainerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Trainer");

        txtBtchNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBtchNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBtchNumActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Batch Number");

        txtStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartActionPerformed(evt);
            }
        });

        tblProgramInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Program ID", "Program Title", "Trainer", "Batch Number", "Start Date", "End Date"
            }
        ));
        tblProgramInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProgramInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProgramInfo);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Start Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("End Date");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel14.setText("PROGRAM LIST");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("PROGRAM INFORMATION");

        cbAscDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbAscDesc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASC", "DESC" }));
        cbAscDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAscDescActionPerformed(evt);
            }
        });

        cbFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFieldName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ProgramId", "ProgramTitle", "Trainer", "BatchNumber", "StartDate", "EndDate" }));

        btnSort.setBackground(new java.awt.Color(102, 255, 102));
        btnSort.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSort.setText("Sort");
        btnSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSortMouseClicked(evt);
            }
        });
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cbAscDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProgramTitle)
                                    .addComponent(txtProgID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTrainer)
                                    .addComponent(txtBtchNum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEnd)
                                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAscDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSort))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProgID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProgramTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtBtchNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProgIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgIDActionPerformed

    private void txtEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseClicked

    void setDefaultRow() {
        DefaultTableModel tbl = (DefaultTableModel) tblProgramInfo.getModel();
        if (tblProgramInfo.getRowCount() > 0) {
            tblProgramInfo.setRowSelectionInterval(0, 0);
            getRow();
        }

    }

     void sortData() {

        String fieldName = cbFieldName.getSelectedItem().toString();
        String order = cbAscDesc.getSelectedItem().toString();
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "SELECT * FROM program ORDER BY " + fieldName + " " + order;
            PreparedStatement pstmnt = conn.prepareStatement(qry);

            ResultSet rslt = pstmnt.executeQuery();
            while (rslt.next()) {
                String pId = rslt.getString("ProgramId");
                String pTitle = rslt.getString("ProgramTitle");
                String trainer = rslt.getString("Trainer");
                String bNo = rslt.getString("BatchNumber");
                String sD = rslt.getString("StartDate");
                String Ed = rslt.getString("EndDate");
               
                String data[] = {pId, pTitle, trainer, bNo, sD, Ed};
                DefaultTableModel tbl = (DefaultTableModel) tblProgramInfo.getModel();

                tbl.addRow(data);
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }

    }
    void viewData() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "SELECT * FROM program";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            ResultSet rslt = pstmnt.executeQuery();

            //      isa-isahin yung data
            while (rslt.next()) {
                String programId = rslt.getString("ProgramId");
                String programTitle = rslt.getString("ProgramTitle");
                String trainer = rslt.getString("Trainer");
                String batchNo = rslt.getString("BatchNumber");
                String startDate = rslt.getString("StartDate");
                String endDate = rslt.getString("EndDate");

                String data[] = {programId, programTitle, trainer, batchNo, startDate, endDate};
                DefaultTableModel tbl = (DefaultTableModel) tblProgramInfo.getModel();

                tbl.addRow(data);
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblProgramInfo.getModel();
        model.setRowCount(0);
    }

    void addData() {
        if (txtProgramTitle.getText().equals("") || txtTrainer.getText().equals("")
                || txtBtchNum.getText().equals("") || txtStart.getText().equals("") || txtEnd.getText().equals("")) {
            showMessageDialog(this, "Incomplete Details");
        } else {
            try {
                String qry = "INSERT INTO `program`(`ProgramId`, `ProgramTitle`, `Trainer`, `BatchNumber`, `StartDate`, `EndDate`) "
                        + "VALUES ( ?,?,?,?,?,?);";
                Connection conn = DriverManager.getConnection(db, "root", null);
                PreparedStatement pstmnt = conn.prepareStatement(qry);
                pstmnt.setString(1, txtProgID.getText());
                pstmnt.setString(2, txtProgramTitle.getText());
                pstmnt.setString(3, txtTrainer.getText());
                pstmnt.setString(4, txtBtchNum.getText());
                pstmnt.setString(5, txtStart.getText());
                pstmnt.setString(6, txtEnd.getText());

                pstmnt.executeUpdate();
                showMessageDialog(this, "Progam Added");

            } catch (SQLException err) {
                err.printStackTrace();
            }
        }

    }

    void updateData() {
        if (txtProgramTitle.getText().equals("") || txtTrainer.getText().equals("")
                || txtBtchNum.getText().equals("") || txtStart.getText().equals("") || txtEnd.getText().equals("")) {
            showMessageDialog(this, "Incomplete Details");
        } else {
            try {
                Connection conn = DriverManager.getConnection(db, "root", null);
                String qry = "UPDATE `program` SET `ProgramTitle`=?,`Trainer`=?,"
                        + "`BatchNumber`=?,`StartDate`=?,`EndDate`=? "
                        + "WHERE ProgramId = ?";
                PreparedStatement pstmnt = conn.prepareStatement(qry);
                pstmnt.setString(1, txtProgramTitle.getText());
                pstmnt.setString(2, txtTrainer.getText());
                pstmnt.setString(3, txtBtchNum.getText());
                pstmnt.setString(4, txtStart.getText());
                pstmnt.setString(5, txtEnd.getText());
                pstmnt.setString(6, txtProgID.getText());

                pstmnt.executeUpdate();
                showMessageDialog(this, "Program Updated");

            } catch (SQLException err) {
                err.printStackTrace();
            }
        }

    }

    void deleteData() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "DELETE FROM program WHERE ProgramId = ?";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            pstmnt.setString(1, txtProgID.getText());

            pstmnt.executeUpdate();
            showMessageDialog(this, "Program Removed");

        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void getRow() {
        DefaultTableModel tbl = (DefaultTableModel) tblProgramInfo.getModel();
        int selectedRowIndex = tblProgramInfo.getSelectedRow();

        txtProgID.setText((tbl.getValueAt(selectedRowIndex, 0)).toString());
        txtProgramTitle.setText((tbl.getValueAt(selectedRowIndex, 1)).toString());
        txtTrainer.setText((tbl.getValueAt(selectedRowIndex, 2)).toString());
        txtBtchNum.setText((tbl.getValueAt(selectedRowIndex, 3)).toString());
        txtStart.setText((tbl.getValueAt(selectedRowIndex, 4)).toString());
        txtEnd.setText((tbl.getValueAt(selectedRowIndex, 5)).toString());
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateData();
        clearTable();
        viewData();
    }//GEN-LAST:event_btnUpdateActionPerformed


    private void txtProgramTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramTitleActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        addData();
        clearTable();
        viewData();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        deleteData();
        clearTable();
        viewData();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrainerActionPerformed

    private void txtBtchNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBtchNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtchNumActionPerformed

    private void txtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartActionPerformed

    private void tblProgramInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProgramInfoMouseClicked
        // TODO add your handling code here:
        getRow();
    }//GEN-LAST:event_tblProgramInfoMouseClicked

    private void cbAscDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAscDescActionPerformed
         
    }//GEN-LAST:event_cbAscDescActionPerformed

    private void btnSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortMouseClicked
        clearTable();
        sortData();
    }//GEN-LAST:event_btnSortMouseClicked

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramIntForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbAscDesc;
    private javax.swing.JComboBox<String> cbFieldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProgramInfo;
    private javax.swing.JTextField txtBtchNum;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtProgID;
    private javax.swing.JTextField txtProgramTitle;
    private javax.swing.JTextField txtStart;
    private javax.swing.JTextField txtTrainer;
    // End of variables declaration//GEN-END:variables
}
