package Admin;

import static Admin.AddStudent.db;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author drewn
 */
public class StudentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form Student
     */
    public StudentForm() {
        initComponents();
        viewData();
        setDefaultRow();
        this.getContentPane().setBackground(new Color(204, 255, 204));
        this.setPreferredSize(new Dimension(1393, 876));


        tblStudentInfo.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS); // this is obvius part
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentInfo = new javax.swing.JTable();
        txtStudentNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtFirstName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        txtMiddleInitial = new javax.swing.JTextField();
        cbAscDesc = new javax.swing.JComboBox<>();
        txtRequirement = new javax.swing.JTextField();
        cbFieldName = new javax.swing.JComboBox<>();
        txtProgramTitle = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtBatchNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbGrade = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSort = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1393, 876));
        setPreferredSize(new java.awt.Dimension(1393, 876));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("StudentNumber:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Middle Initial:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Requirement Status:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Batch No.");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Program Title");

        tblStudentInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Number", "First Name", "Middle Inital", "Last Name", "Address", "Requirement Status", "Password", "BatchNo", "ProgramTitle", "Email", "Grade"
            }
        ));
        tblStudentInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudentInfo);

        txtStudentNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Grade");

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Add Student");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(102, 255, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setText("Update Student");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDelete.setBackground(new java.awt.Color(102, 255, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Delete Student");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtMiddleInitial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbAscDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbAscDesc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASC", "DESC" }));
        cbAscDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAscDescActionPerformed(evt);
            }
        });

        txtRequirement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRequirement.setText("Passed");
        txtRequirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequirementActionPerformed(evt);
            }
        });

        cbFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFieldName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "StudentNumber", "FirstName", "MiddleInitial", "LastName", "Address", "Requirement_Status", "Pass_word", "BatchNo", "ProgramTitle", "Email", "Grade" }));
        cbFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFieldNameActionPerformed(evt);
            }
        });

        txtProgramTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProgramTitle.setText("Java Programming NC3");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setText("pw");
        txtPassword.setToolTipText("");

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtBatchNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBatchNo.setText("7");
        txtBatchNo.setToolTipText("");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Training On Going", "Competent", "Incompetent", " ", " " }));
        cbGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGradeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("STUDENT INFORMATION");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel14.setText("STUDENT LIST");

        btnSort.setBackground(new java.awt.Color(102, 255, 102));
        btnSort.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSort.setText("Sort");
        btnSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSortMouseClicked(evt);
            }
        });
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMiddleInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(89, 89, 89))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(17, 17, 17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtProgramTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(cbGrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cbAscDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAscDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSort))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMiddleInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtProgramTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(151, 151, 151))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setDefaultRow() {
        DefaultTableModel tbl = (DefaultTableModel) tblStudentInfo.getModel();
        if (tblStudentInfo.getRowCount() > 0) {
            tblStudentInfo.setRowSelectionInterval(0, 0);
            getRow();
        }

    }

    void sortData() {

        String fieldName = cbFieldName.getSelectedItem().toString();
        String order = cbAscDesc.getSelectedItem().toString();
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "SELECT * FROM student_info ORDER BY " + fieldName + " " + order;
            PreparedStatement pstmnt = conn.prepareStatement(qry);

            ResultSet rslt = pstmnt.executeQuery();
            System.out.println("SUCCESS!");
            while (rslt.next()) {
                String studno = rslt.getString("StudentNumber");
                String fname = rslt.getString("FirstName");
                String mi = rslt.getString("MiddleInitial");
                String lname = rslt.getString("LastName");
                String add = rslt.getString("Address");
                String req = rslt.getString("Requirement_Status");
                String pw = rslt.getString("Pass_word");
                String batchno = rslt.getString("BatchNo");
                String prog = rslt.getString("ProgramTitle");
                String email = rslt.getString("Email");
                String grade = rslt.getString("Grade");

                String data[] = {studno, fname, mi, lname, add, req, pw, batchno,
                    prog, email, grade};
                DefaultTableModel tbl = (DefaultTableModel) tblStudentInfo.getModel();

                tbl.addRow(data);
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }

    }

    void deleteData() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "DELETE FROM student_info WHERE StudentNumber = ?";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            pstmnt.setString(1, txtStudentNumber.getText());

            pstmnt.executeUpdate();
            showMessageDialog(this, "Student Removed");

//            cleanUp
//            
        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void updateData() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "UPDATE `student_info` SET `FirstName`= ?,`MiddleInitial`=?,`LastName`=?,`Address`=?,`Requirement_Status`=?,"
                    + "`Pass_word`=?,`BatchNo`=?,`ProgramTitle`=?,`Email`=?,`Grade`=? "
                    + "WHERE StudentNumber = ?";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
//            pstmnt.setString(1, txtStudentNumber.getText());
            pstmnt.setString(1, txtFirstName.getText());
            pstmnt.setString(2, txtMiddleInitial.getText());
            pstmnt.setString(3, txtLastName.getText());
            pstmnt.setString(4, txtAddress.getText());
            pstmnt.setString(5, txtRequirement.getText());
            pstmnt.setString(6, txtPassword.getText());
            pstmnt.setString(7, txtBatchNo.getText());
            pstmnt.setString(8, txtProgramTitle.getText());
            pstmnt.setString(9, txtEmail.getText());
            pstmnt.setString(10, cbGrade.getSelectedItem().toString());
            pstmnt.setString(11, txtStudentNumber.getText());

            pstmnt.executeUpdate();
            showMessageDialog(this, "Data Inserted");

//            cleanUp
//            
        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void viewData() {
        try {
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "SELECT * FROM student_info";
            PreparedStatement pstmnt = conn.prepareStatement(qry);
            ResultSet rslt = pstmnt.executeQuery();
            System.out.println("DAPAT GUMAGANA" + this);
            //      isa-isahin yung data
            while (rslt.next()) {
                String studno = rslt.getString("StudentNumber");
                String fname = rslt.getString("FirstName");
                String mi = rslt.getString("MiddleInitial");
                String lname = rslt.getString("LastName");
                String add = rslt.getString("Address");
                String req = rslt.getString("Requirement_Status");
                String pw = rslt.getString("Pass_word");
                String batchno = rslt.getString("BatchNo");
                String prog = rslt.getString("ProgramTitle");
                String email = rslt.getString("Email");
                String grade = rslt.getString("Grade");

                String data[] = {studno, fname, mi, lname, add, req, pw, batchno,
                    prog, email, grade};
                DefaultTableModel tbl = (DefaultTableModel) tblStudentInfo.getModel();

                tbl.addRow(data);
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }
    }

    void getRow() {
        DefaultTableModel tbl = (DefaultTableModel) tblStudentInfo.getModel();
        int selectedRowIndex = tblStudentInfo.getSelectedRow();

        txtStudentNumber.setText((tbl.getValueAt(selectedRowIndex, 0)).toString());
        txtFirstName.setText((tbl.getValueAt(selectedRowIndex, 1)).toString());
        txtMiddleInitial.setText((tbl.getValueAt(selectedRowIndex, 2)).toString());
        txtLastName.setText((tbl.getValueAt(selectedRowIndex, 3)).toString());
        txtAddress.setText((tbl.getValueAt(selectedRowIndex, 4)).toString());
        txtRequirement.setText((tbl.getValueAt(selectedRowIndex, 5)).toString());
        txtPassword.setText((tbl.getValueAt(selectedRowIndex, 6)).toString());
        txtBatchNo.setText((tbl.getValueAt(selectedRowIndex, 7)).toString());
        txtProgramTitle.setText((tbl.getValueAt(selectedRowIndex, 8)).toString());
        txtEmail.setText((tbl.getValueAt(selectedRowIndex, 9)).toString());
        cbGrade.setSelectedItem((tbl.getValueAt(selectedRowIndex, 10)).toString());
    }

    void addData() {
        if (txtFirstName.getText().equals("") || txtMiddleInitial.getText().equals("") || txtLastName.getText().equals("")
                || txtAddress.getText().equals("") || txtRequirement.getText().equals("") || txtPassword.getText().equals("")
                || txtBatchNo.getText().equals("") || txtProgramTitle.getText().equals("") || txtEmail.getText().equals("")) {
            showMessageDialog(null, "Kulang");
        } else {
            try {
                String qry = "INSERT INTO `student_info`(`StudentNumber`, `FirstName`, `MiddleInitial`, `LastName`, "
                        + "`Address`, `Requirement_Status`, `Pass_word`, `BatchNo`, `ProgramTitle`, `Email`, `Grade`) "
                        + "VALUES ( null, ?, ?,?,?,?,?,?,?,?,?);";
                Connection conn = DriverManager.getConnection(db, "root", null);
                PreparedStatement pstmnt = conn.prepareStatement(qry);
//            pstmnt.setString(1, txtStudentNumber.getText());
                pstmnt.setString(1, txtFirstName.getText());
                pstmnt.setString(2, txtMiddleInitial.getText());
                pstmnt.setString(3, txtLastName.getText());
                pstmnt.setString(4, txtAddress.getText());
                pstmnt.setString(5, txtRequirement.getText());
                pstmnt.setString(6, txtPassword.getText());
                pstmnt.setString(7, txtBatchNo.getText());
                pstmnt.setString(8, txtProgramTitle.getText());
                pstmnt.setString(9, txtEmail.getText());
                pstmnt.setString(10, cbGrade.getSelectedItem().toString());

                pstmnt.executeUpdate();
                showMessageDialog(this, "Data Inserted");

//            cleanUp
//            
            } catch (SQLException err) {
                err.printStackTrace();
            }

        }

    }

    void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudentInfo.getModel();
        model.setRowCount(0);
    }


    private void tblStudentInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentInfoMouseClicked
        // TODO add your handling code here:
        getRow();
    }//GEN-LAST:event_tblStudentInfoMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        addData();
        clearTable();
        viewData();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateData();
        clearTable();
        viewData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        deleteData();
        clearTable();
        viewData();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtRequirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequirementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequirementActionPerformed

    private void cbGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGradeActionPerformed

    private void cbFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFieldNameActionPerformed

    private void cbAscDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAscDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAscDescActionPerformed

    private void btnSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortMouseClicked
        clearTable();
        sortData();
    }//GEN-LAST:event_btnSortMouseClicked

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbAscDesc;
    private javax.swing.JComboBox<String> cbFieldName;
    private javax.swing.JComboBox<String> cbGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudentInfo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBatchNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleInitial;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtProgramTitle;
    private javax.swing.JTextField txtRequirement;
    private javax.swing.JTextField txtStudentNumber;
    // End of variables declaration//GEN-END:variables
}
